### PR TITLE
Update WRFCHEM section for NRT Chem

### PR DESCRIPTION
**Pull request by weiwilliam**
The code has been merged with the latest master branch (commit: [528725c](https://github.com/weiwilliam/Wx-AQ_LuLab/commit/528725cf249e9d33b6f387d3b9cf65a7d105f3b2)).

- [x] Test code with a couple of NRT retro cycles.

### CODE REVIEW

**Comment by weiwilliam** [comment]
@dpgrogan27 I saw you checked the box, is everything fine with the updated NRTChem?

**Comment by dpgrogan27** [comment]
Yes, I ran a few cycles from yesterday sucessful. I have made setup a cron job for tomorrows runs
________________________________

**Comment by weiwilliam** [comment]
@Hui4ying3LUO2 Huiying, I found out why your branch became messy.
Today I use 'git merge master' at NRTChem, it showed conflicts at run_wrfgsi.bash and stopped merging.
That's the same status you showed.
I fixed it by following the hints from the messages from Git command.
The steps are
1. Solve the conflicts in run_wrfgsi.bash
2. git add run_wrfgsi.bash
3. git commit -m'<messages>'
4. git push origin

**Comment by weiwilliam** [comment]
Great! If @Hui4ying3LUO2 is fine with this, then it can be merged to master.
After the master branch was updated, I would recommend you clone a clean repository with master only for running the NRT system (i.e., calling from cron job).
By doing this, when we introduce new features into the system and would like to run in the NRT system in the future, you can easily get the updates by 'git pull' in that repository folder.
In my case, I currently have 'Wx-AQ' and 'Wx-AQ_dev' under my home directory.
I do the development in 'Wx-AQ_dev' and run cron jobs of prepdata scripts from 'Wx-AQ'.

**Comment by weiwilliam** [comment]
The usage of WACCM data and updating the emission files for WRFChem forecasts mentioned in #26 are solved by this PR.

**Comment by weiwilliam** [comment]
@dpgrogan27 @Hui4ying3LUO2 
I suggest changing dir_wrf and dir_moz in create_emiinp_mozbc.bash to './'.
In this way, the problem caused by filename over 70 characters can be avoided.
We can also add 'cd ${mozdir}' to ensure that create_emiinp_mozbc.bash generates .inp file in ${mozdir} correctly.

**Comment by Hui4ying3LUO2** [comment]
Sure. Thanks for the suggestion! If this works no problem, the run folder
name can be reverted back.

On Tue, Jun 14, 2022 at 5:23 PM weiwilliam ***@***.***> wrote:

> *Message sent from a system outside of UConn.*
>
> @dpgrogan27 @Hui4ying3LUO2
> I suggest changing dir_wrf and dir_moz in create_emiinp_mozbc.bash to './'.
> In this way, the problem caused by filename over 70 characters can be
> avoided.
> We can also add 'cd ${mozdir}' to ensure that create_emiinp_mozbc.bash
> generates .inp file in ${mozdir} correctly.
>
> —
> Reply to this email directly, view it on GitHub
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fweiwilliam%2FWx-AQ_LuLab%2Fpull%2F33%23issuecomment-1155725621&data=05%7C01%7C%7C8b4ba583f44a436a4fd208da4e4c27a7%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C637908386224755756%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=n2gp4%2BQohQ181sK031Xsdfl7t3qI9yY%2Bkii3IJuF85Q%3D&reserved=0>,
> or unsubscribe
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPQGWUNC4PAP2QWFHXPLHFDVPDZ53ANCNFSM5YO7UATA&data=05%7C01%7C%7C8b4ba583f44a436a4fd208da4e4c27a7%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C637908386224755756%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zNYh%2FHePv8pU%2BClMRVvo6Si4WNJp6pTJFVkuayyYtss%3D&reserved=0>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 
Huiying

**Comment by weiwilliam** [comment]
- [ ] include #36 in this PR

**Pull request merged**
