### PR TITLE
Update create_namelist.input.bashChin

### PR DESCRIPTION
**Pull request by clin-nick**
modify &chem namelist for chem_opt=114,
set emiss_opt = 11 , biomass_burn_opt =4

### CODE REVIEW

**Comment by weiwilliam** [comment]
@clin-nick, Do you suggest the NRT system uses this configuration? Or it's a temporary setting for testing.

**Comment by clin-nick** [comment]
Yes, the NRT system using 114 should use this configuration.

**Comment by weiwilliam** [comment]
Okay, then please update the create_namelist.input.bash as well.
Modify it and push to your branch "clin-nick-WRFCHEM" again.
I recall it will automatically amend this pull request.

**Comment by weiwilliam** [comment]
@clin-nick I modified the create_namelist.input.bash like you did in create_namelist.input.bashChin.

**Pull request merged**
