### PR TITLE
remove colon for wrfout, met_em, and figures

### PR DESCRIPTION
**Pull request by weiwilliam**
This PR addresses the colon issue #81  in the file name.
- [x] wrfout in store_case.bash
- [x] met_em in store_case.bash
- [x] figures in spa_O3_PM25_NYS_hr.py

### CODE REVIEW

**Review by SarahLu-NOAA — APPROVED** [review]
PR approved

**Comment by weiwilliam** [comment]
@clin-nick Can you double-check if the modification to plotdata/spa_O3_PM25_NYS_hr.py is good to go?
I gave it a try, it can generate plots properly (see sample files under /network/asrc/scratch/lulab/sw651133/test/imgout).
The new filename is YYYY-MM-DD_HHZ_NYS.png.

**Review by clin-nick — APPROVED** [review]
The plotting script works smoothly. No issues were found for bash files.

**Comment by weiwilliam** [comment]
@clin-nick @SarahLu-NOAA Thank you!
@dpgrogan27 The updates are available in master. Please merge it to update your NRT folder. Thank you!

**Pull request merged**
