### PR TITLE
Update the WRFCHEM_INPUT.sh to use NEI 12km data

### PR DESCRIPTION
**Pull request by weiwilliam**
This PR resolves issue #50.
It will fix the missing data of the 4km NEI for the 4 km domain WRF-Chem run.

To-do list:
- [x] update with the latest master
- [x] include the python script to fill missing data outside of 4 km NEI with global emission for the summer (May-Sep) period (@clin-nick, please provide the script.)
- [x] modify the if-statement structure to use 12 km NEI for the months (Jan-Apr and Oct-Dec) without 4 km NEI

Please add any detail I missed.

### CODE REVIEW

**Comment by clin-nick** [comment]
Is there any way to commit directly to this pull request?

**Comment by weiwilliam** [comment]
@clin-nick Checkout the 'NRTChem' branch and work on that. Every commit you made and pushed will appear in this PR.

**Comment by clin-nick** [comment]
Still need to add if loop to create Anth emission for LISTOS and non-LISTOS period, separately.

**Comment by weiwilliam** [comment]
hires_NEI is introduced to check if the forecast period falls between May to Sep.
When it is 1, WRFCHEM_INPUT will merge 12+4 km NEI for the inner domain.

**Comment by weiwilliam** [comment]
@clin-nick, I found APIN in 4km NEI is not available in 12km NEI, so I add "if not io" to merge_anth.py.
Please check if it's okay.
I check the create_emiinp_anth4km.bash and create_emiinp_anth.bash
The emis_map(22) has a different name, APIN in 4km; C10H16 in 12km.
Can you confirm whether it is fine or need to be corrected?

@SarahLu-NOAA Now the WRFCHEM_INPUT can manipulate LISTOS period as well.
I gave it a test within LISTOS period and it successfully finished, so the anth emission merging script should work properly.
Once @clin-nick confirm then we can conclude v1.1.0.

**Comment by clin-nick** [comment]
I forgot to update the create_emiinp_anth.bash.
C10H16 should be changed to APIN.

**Comment by weiwilliam** [comment]
@clin-nick, great, let me update it.

**Comment by weiwilliam** [comment]
@SarahLu-NOAA @clin-nick, it's ready. I can merge it after one of you approve it.

**Review by clin-nick — APPROVED** [review]
finish review

**Pull request merged**
