### PR TITLE
Include the domain 2 DA and enhance some aspects

### PR DESCRIPTION
**Pull request by weiwilliam**
This PR includes the issues #6, #13, #15, #16, #19, and #20.
Before merging to the master branch, the following tasks are needed to check.
- [x] Finish two cycles of retro run during LISTOS period
- [x] Correct prepbufr data symbolic link
- [x] No issue to finish GSI over two domains
- [x] Correct namelist.input
- [x] Outputs are archived
- [x] Monitor the cronjob for data pulling and NYSM appending

### CODE REVIEW

**Comment by weiwilliam** [comment]
The commit for issue #22 has been included.

**Comment by weiwilliam** [comment]
Hi @Hui4ying3LUO2 @clin-nick, 
Can one of you give it a try for two cycles run?
It works on my end, but it is better to have a sanity check.
I would suggest the following steps:
1. git clone git@github.com:weiwilliam/Wx-AQ_LuLab.git [folder]
2. cd [folder]
3. git checkout swei_develop
4. Try the chem_opt 0 (much faster);
5. Select the start_date and last_date
6. Good to go 
Note: You can see the job status of GSI now, but it prints out everything. You may want to run the top-driver with "./run_wrfgsi.bash > ./log 2>&1 &".

**Comment by clin-nick** [comment]
The system works on my end. (chem=0, test period: 2018071418-2018071500)

**Comment by weiwilliam** [comment]
Great, everything in wrf folder looks good?

**Comment by Hui4ying3LUO2** [comment]
Thank you, Shih-Wei and Chin-An!

On Tue, Apr 26, 2022 at 4:34 PM clin-nick ***@***.***> wrote:

> *Message sent from a system outside of UConn.*
>
> The system works on my end. (chem=0, test period: 2018071418-2018071500)
>
> —
> Reply to this email directly, view it on GitHub
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fweiwilliam%2FWx-AQ_LuLab%2Fpull%2F21%23issuecomment-1110223861&data=05%7C01%7C%7C473a429eb23d417f020608da27c42f13%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C637866020793545763%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=N1Dt57YxUcwdPC8Ns7Mv5faUX05OOKZDSihoEA7fUZo%3D&reserved=0>,
> or unsubscribe
> <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPQGWUMCWUP7F3KOJHBNFZ3VHBHN3ANCNFSM5UKUUDBQ&data=05%7C01%7C%7C473a429eb23d417f020608da27c42f13%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C637866020793545763%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aymjTOXWmdczTkfjhn7hIkyviexut0NNytrU%2BmZTmfc%3D&reserved=0>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 
*........................................................................................*
*    Huiying Luo * Ph.D.

    Department of Civil and Environmental Engineering

    University of Connecticut

    261 Glenbrook Road

    Storrs, CT 06269-3037
    Phone: 860-617-3285
*........................................................................................*

**Pull request merged**
