### PR TITLE
Introduce the new single domain configuration and updated workflow for ndown ready

### PR DESCRIPTION
**Pull request by weiwilliam**
Due to the limited resource, the domain configuration is tweaked for a single domain, and nested in ACOM domain 1.
This PR includes the followings:
- update scripts to manipulate single domain runs. #47 
- the code for future updates of ndown in run_wrfgsi.bash is introduced.
- the WRFCHEM_INPUT.bash is updated accordingly for the single domain run.
- now it can purge run (1 day ago) and out (7 days ago) folders by setting 'clean_up' to 1 at beginning of run_wrfgsi.bash. #46 
- partition variable is introduced into each run_* script to submit jobs to 'kratos' (kratos) or 'uagc' (batch) node.
- no GSI option can be controlled by da_doms variable now. #28 
- now run_wrfgsi.bash output time stamp for each step into the logfile.
- the upstream chemistry files are checked by datacheck_gfs.bash and the return code is used to determine the chemistry boundary condition and running ndown or not.
- the fort.xxx files created by GSI are lumped into gsistat.d0?.yyyymmddhh for visualization purposes. 
- store_case.bash is modified accordingly.

I have run this branch for 4 cycles. 
Please check this branch out and give it a try to see if there are any problems.

### CODE REVIEW

**Comment by weiwilliam** [comment]
@clin-nick @dpgrogan27 @Hui4ying3LUO2 
You can try any period for it.
I've found running WRF-Chem with uagc nodes seems not stable.
I'll work on it.

**Comment by weiwilliam** [comment]
Running WRF on uagc nodes seems not stable, so the new commit makes WRF on kratos partition.

**Comment by weiwilliam** [comment]
@clin-nick /network/asrc/scratch/lulab/sw651133/wx-aq_run/2022070918/wrf
Please take a look. I'm trying DFI to see if it helps, so please ignore rsl files now.
I can run it again if you need.

**Comment by weiwilliam** [comment]
@clin-nick @dpgrogan27 @Hui4ying3LUO2
The new configuration completed the cycle was problematic.
I have the outputs from July 4 12Z to July 9 00Z now.
Did you see any other problems with the scripts?

**Comment by clin-nick** [comment]
I saw the wrfouts in 2022070900, 2022070906, and 2022070912 are created successfully.
Does that mean only 2022070918 has issues?

**Comment by weiwilliam** [comment]
@clin-nick No, the one encountered problem was 2022070900. 
It successfully finished that cycle after implementing the option to update the Chem ICs at the first cycle only.
Hopefully, it can last up to a month at least.
I think if you don't see other big issues at this point, we can restart the cron job once my parallel run catches up with the real-time cycle.

**Comment by weiwilliam** [comment]
@clin-nick @dpgrogan27 @Hui4ying3LUO2 
As discussed today, we can restart the NRT run.
If you don't see other big issues in terms of running the cycling system, please approve this PR.

**Review by clin-nick — APPROVED** [review]
I do not see big issues.
We can start the forecast system and monitor that.

**Pull request merged**
